### ISSUE TITLE
node compatibility

### ISSUE THREAD

**Issue by bluej100** [mholt/PapaParse#140]
It would be nice to have node compatibility as part of this project, including streamers for Node resources.

I think I'll work on this after the Grunt build and streamer refactoring pull requests merge.

**Comment by robd** [comment]
I just wanted to update this issue with the progress we've made. As discussed over in #167, I think PapaParse should support basic parsing etc with Node now that #172 has been merged. It might be good to update the PapaParse docs to indicate that there is now some Node support.

There is more cleanup possible in this area, for example, to improve the separation of web dependent features such as web workers, remote file parsing, file object support, multithreading etc, so that they are never loaded / supported when executed in a Node environment. We could also look at Node ports of some of these if they make sense. I'm not sure what the use cases are there, but it might be sensible to prioritize the possible Node features based on what's needed.

Another question is whether BabyParse is still required. AFAICT BabyParse doesn't include any tests for behaviour on Node, so it's a bit difficult to know what functionality is or isn't supported there, but I think it's possible that PapaParse now supports everything that BabyParse does. Perhaps @Rich-Harris could see if PapaParse would now work for his application. 

From a maintenance perspective, and for newcomers to PapaParse, I think it would be more straightforward not to have 2 projects (ie Baby and Papa) both supporting node, so it might make sense to sunset BabyParse and pick up Node support in Papa directly.

**Comment by mholt** [comment]
I would like to sunset Baby Parse as soon as Papa Parse can run in Node. Like you said -- and majorly thanks to you and Braden -- we are getting closer to that point.

While I don't think we need to implement multi-threading for Node environments, it might be handy to stream and download files using some native Node facilities. Node compatibility is something that I will not personally implement with Papa Parse. (I don't have Node installed because I don't use Node, and I have no personal interest in developing for it at this time.) However, I support anyone who is willing to make it happen.

First, let's make what we already have play nicely in Node by making sure the browser-only features stay out of the way. Once Papa Parse can run out-of-the-box in a Node environment, I will make a release, after which we can consider adding bells and whistles.

Thanks for all your contributions thus far!

**Comment by robd** [comment]
OK, cool. I'm also not using node, but if I have time I will have a crack at better separating the web specific stuff somehow. 

I think the latest version PP will already work with Node without further modifications needed by the user. So could you expand on what you're thinking when you say 'out-of-the-box' in a Node env?

Thanks!

**Comment by mholt** [comment]
In that case, let's just verify that and I'll prepare a (minor) release as soon as I get a chance. That'll make a good delineation before we go forward.

**Comment by robd** [comment]
OK cool. I guess the only other thing is to update the readme / docs site. Do you want me to submit a PR for the docs? I'll email you and Rich Harris to see if he has a view on whether BabyParse is now no longer needed. I'm not sure if he gets notified on this issue via Github.

**Comment by mholt** [comment]
You're welcome to submit a PR for the site or readme or whatever else, sure! And the email is a good idea. I know Rich is pretty busy, but he's usually good about emails.

**Comment by bmcorum** [comment]
Matt,

I should be able to rather easily add the changes I recently made to BabyParse for file parsing into PapaParse for use with node. The issue I am running into is that I will be unable to submit a pull request to PapaParse since I have previously forked BabyParse. Wether or not you or Rich plan on further supporting BabyParse, it really should be a separate standalone repo all to itself and not a fork of PapaParse (there is an option in the settings to 'duplicate the repository' which should allow users to fork both PapaParse and BabyParse).

**Comment by ghostsquad** [comment]
:+1:

**Comment by lunatixcoder** [comment]
PapaParse works fine in node for me.  Is this still an issue?

**Comment by pokoli** [comment]
Node streams are suported since the [release 4.2.0](https://github.com/mholt/PapaParse/releases/tag/4.2.0), so I'm closing this issue.

@lunatixcoder thanks for the triage 👍
