### ISSUE TITLE
Numeric value with comma (European-formatted numbers)

### ISSUE THREAD

**Issue by 2803media** [mholt/PapaParse#143]
Hi I use papaparse and I wonder if there is a way to convert numeric value with comma instead of dot with dynamicTyping: true option, it doesn't seem to work. Thanks

**Comment by MauroJurada** [comment]
I'm really struggling to get this to work.
Error I'm getting is: 
TypeError: results.data[i][j].replace is not a function

Since I'm using headers this is how I've set it up like but replace can't be used on objects like this.
![image](https://user-images.githubusercontent.com/37582356/45301687-bc1eb280-b511-11e8-8610-9528cac1f95e.png)

How should I go about solving this? 
I appreciate any help!

**Comment by Braintelligence** [comment]
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
could be used on each value for those who do input American numbers but want to receive an output with European numbers.
