### ISSUE TITLE
IE before IE9 and ExtendScript don't have an .indexOf() function for Array

### ISSUE THREAD

**Issue by grefel** [mholt/PapaParse#147]
`indexOf()` was added to the ECMA-262 standard in the 5th edition; As such it may not be present in all Implementations. PapaParse does not work with ExtendScript (Adobe) and presumably not with IE8 or lower. 

I see two possible solutions:

**1. Add ECMA262-5 Array methods if not supported natively**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

`if (!('indexOf' in Array.prototype)) { ...`

**2. Add `join("")` to `Papa.BAD_DELIMITERS`**
Need to be changed in lines 375, 1126, 1135 and 1517
This should work with the current `Papa.BAD_DELIMITERS` but could probalby go wrong after adding more `Papa.BAD_DELIMITERS`

**Comment by mholt** [comment]
Thanks for reporting this -- I had no idea about ExtendScript...

Papa's not in the business of supporting old browsers. The library would quickly grow in size and complexity. My recommendation would be, for those that still need to support old IE and, I guess, ExtendScript, to add that polyfill to their page themselves and then it should work.

**Comment by grefel** [comment]
I'm fine with this recommendation. The reason for asking was, that I'm writing a book about Adobe InDesign Scripting (ExtendScript). The target audience is including beginners which are not aware of polyfills.
I've a chapter about CSV parsing which is a common task for Database Publishing but don't like the idea to use an external Library which has to be changed. 
But I can totally understand your idea about not supporting old Implementations, but ExtendScript (for all Adobe Creative Suite Applications) is not to be updated any time soon.

**Comment by mholt** [comment]
Well, I admit, that's a pretty unexpected scenario. I'm not familiar with ExtendScript, but I'm pretty sure Papa Parse doesn't have to be modified to use the polyfill. Unless... does the polyfill have to be added inside Papa Parse in order to work in ExtendScript? (For browser apps, it can just be added to the page without needing to modify the library.)

I'll let you choose.

If polyfills are outside the scope of your book (even just a footnote or paragraph or something?) I'd be willing to add the polyfill to Papa Parse -- but be aware that it wouldn't be permanent; Papa Parse will continue to support modern browsers/environments. If you choose this option, consider that the polyfill may be removed months or years in the (near-)future to reduce cruft.

The other option is that you could just fork the project and add the polyfill to your fork. (Granted, merging in the latest from HEAD every once in a while might get annoying.)

So there's three options so far:

1. Use a footnote/paragraph to explain polyfills or just the concept that ExtendScript needs a little bit of a push
2. I can add the polyfill to Papa Parse, but it probably won't be permanent
3. You can add the polyfill to a fork of Papa Parse and link to that instead

Let me know which you prefer! (or if there's another option I'm missing)

**Comment by grefel** [comment]
Your help and ideas are much appreciated. Thanks for the great Library by the way! 

I will add the polyfill in my PapaParse CSV example and explain it in short. My editor won't be happy ("keep it simple ... ") but I think this is in the end the real solution and can be helpful in with other libraries as well. After finishing my book, where I'm pressed a little, I'll post a blog post and let you know.

**Comment by mholt** [comment]
No problem, and thanks for understanding! You can tell your editor it was my fault, even show him/her this issue if you'd like.
