### ISSUE TITLE
Can't load PapaParse with a script loader

### ISSUE THREAD

**Issue by ejain** [mholt/PapaParse#148]
Using a script loader like LAB.js, I get this error:

    Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
    (index):204 error Uncaught TypeError: Cannot read property 'previousSibling' of null papaparse-4.0.7.min.js 6
    papaparse-4.0.7.min.js:6 Uncaught TypeError: Cannot read property 'previousSibling' of null

What is the PapaParse script trying to write into my document? BabyParse btw works fine.

**Comment by mholt** [comment]
Papa Parse writes to the DOM to obtain the path to itself, which is required for worker threads. The fix for the current release is to hard-code your script's path or remove the line that detects it.

However, [a fix has already been committed to master](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L157) on the un-minified version which allows you to load Papa asynchronously. It detects async loading and, if so, expects you to set the Papa.SCRIPT_PATH variable manually. I jumped the gun a bit; there's [already docs](http://papaparse.com/docs#extras) explaining this variable, but you'll have to use the un-minified latest on master for right now to use it.

I'm just wrapping up a few more pull requests/issues before I do a release, which should be soon.

**Comment by jpdevries** [comment]
I've read the docs
> The relative path to Papa Parse. This is automatically detected when Papa Parse is loaded synchronously. However, if you load Papa Parse asynchronously (e.g. with RequireJS), you need to set this variable manually in order to use Web Workers. (In those cases, this variable is not read-only and you should set it!)

and looking at the current source I still don't understand how you are to set Papa.SCRIPT_PATH without modifying the `papaparse.js` source file. Is  it possible to set this without modifying the source?

**Comment by mholt** [comment]
Just do `Papa.SCRIPT_PATH = "path_to_script/papaparse.js` before you load it?

**Comment by richard-jones** [comment]
Sorry to revive an old thread, but I'm having a similar issue.  I'm loading PapaParse with RequireJS, but I don't even get so far as being able to do 

    Papa.SCRIPT_PATH = "path_to_script/papaparse.js";

as Papa isn't available at all, even after the page is loaded.

Is there some other non-code-modifying workaround for asynchronous loading?  Something I can do, say, before requirejs is invoked?
