### ISSUE TITLE
Detected column type information in meta

### ISSUE THREAD

**Issue by KrishnaPG** [mholt/PapaParse#151]
Presently meta information contains only the field names and not their detected datatype. When the option 'dynamic typing' is used, there should a mechanism for user to identify which type was recognized for which column by the parser.

The *fields* should contain column names as well as their data type.

**Comment by mholt** [comment]
Thanks for the suggestion!

Why is the data type important? What do we do if the column doesn't have a consistent type?

**Comment by KrishnaPG** [comment]
Thank you. This is helpful for standardization (such as: http://data.okfn.org/tools/create ).

As for column not being consistent, the existing error mechanism can be reused. That particular row-column pair (cell) would be tagged as 'expected <typeX> but got <typeY>' in the errors.

Typically, the first 'n' rows (n configurable by user, defaults to 5 / 10) are used for detecting the column type - but I believe the existing implementation of dynamic typing should do.

**Comment by mholt** [comment]
The purpose of dynamicTyping is mainly to make mathematical calculations more convenient. My initial impulse is to leave data verification to the user (or another library), since technically "the wrong type" (which isn't even a concept in CSV data) won't produce a *parse* error. Semantics are up to your application.
