### ISSUE TITLE
"TooManyFields" error when CSV file has the first line empty

### ISSUE THREAD

**Issue by vbenso** [mholt/PapaParse#154]
Parsing the following data will, papa will believe that the file has only one column, and will give the "TooManyFields" error while parsing the rest of the file.
Is there a parameter to make it ignore the first line? Shouldn't it ignore the first line in this case given that  the config sets  skipEmptyLines to true?

"FILE BEGINS IN THE NEXT LINE - THE EMPTY ONE"

Tipo;Data;Amostra;Solicitante;Proprietário;Propriedade;Gleba;Identificação;P;MO;V%;%Al (CTC Efetiva);S;Argila;Silte;Areia;CF;pH;H+Al;Al;K;Ca;Mg;SB;C.T.C.;
;;;;;;;;Resina;Na2Cr2O7;-;-;Ca(H2PO4)2;Hexa+NaOH;Hexa+NaOH;Hexa+NaOH;-;CaCl2;SMP;KCl;Resina;Resina;Resina;-;-;
;;;;;;;;mg/dm³;g/dm³;%;%;mg/dm³;g/Kg;g/Kg;g/Kg;-;-;mmolc/dm³;mmolc/dm³;mmolc/dm³;mmolc/dm³;mmolc/dm³;mmolc/dm³;mmolc/dm³;
Solo;18/08/2014;28902/2014;Precisagro Serviços Agrícolas Ltda ME;Mirian Damaso da Silveira Rauen;João Paulo/Papanduva-SC;;Contorno Miriam João Paulo - Amostra 0  0-20 cm;31;39;36;23,8;5;656;310;34;3;4,2;187;33,2;6,5;67;33;106,5;293,5;
"FILE ENDS HERE"

**Comment by mholt** [comment]
Yes, it should. Strange, when I enable `skipEmptyLines` in the player and parse your input (with the blank line at the beginning), it populates the header fields properly. Is this what you want?

![headerrow](https://cloud.githubusercontent.com/assets/1128849/5708987/13d4616a-9a53-11e4-94d8-a09e772d3686.png)

**Comment by vbenso** [comment]
Trying on the player using the proper .csv file, instead of the
copied/pasted one from the previous message, this is what I got from the
player:

[image: Inline image 1]

Victor A. P. Benso
Precisagro
Major Vieira - SC
(47) 9922-9599

**Comment by vbenso** [comment]
This is the original .csv file.

Victor A. P. Benso
Precisagro
Major Vieira - SC
(47) 9922-9599

**Comment by mholt** [comment]
I think GitHub is stripping the attachments... you can email me directly if you want it to remain private.

**Comment by mholt** [comment]
Well, @vbenso, I hate to break it to you, but it turns out that your first line isn't actually empty.

![screen shot 2015-01-12 at 3 54 10 pm](https://cloud.githubusercontent.com/assets/1128849/5712887/650f6000-9a73-11e4-995a-c59d2f4d2954.png)

There's actually an invisible control character there (CR, or `\r`). According to the CSV syntax, that CR is part of the data. Your file only has 2 CR characters, but it has 15 LF characters. I recommend you sanitize your files to ensure line endings are consistent. You can set the line endings with the `newline` property if auto-detection isn't reliable. You can also strip extra whitespace before the header row with something like `.replace(/\s*/, "")`.

Good luck!
