### ISSUE TITLE
Not in Bower Repo?

### ISSUE THREAD

**Issue by coleHafner** [mholt/PapaParse#158]
I get an ENOTFOUND when trying to bower update papaparse. bower search also comes up with no results. I see that your package name is papaparse, so those match and I just cleaned my cache. Any suggestions?

**Comment by mholt** [comment]
Heh, sorry about that. This is part of #152 and things started getting crazy sometime after #17. I've never used Bower, but somehow [it ended up on Bower under three names](https://github.com/bower/bower/issues/120#issuecomment-70099014). I just [had all of them unregistered](https://github.com/bower/bower/issues/120#issuecomment-70288132) so that I could register it more officially, which I'm doing as we speak. I had no idea it had "1000's of hits" on Bower so, well, whoops.

Stay tuned.

**Comment by mholt** [comment]
Okay, I just ran

```bash
$ bower register papaparse git://github.com/mholt/PapaParse.git
```

so Papa Parse should be available again under the name `papaparse`. I went with this name because it is consistent with the package name on npm.

Sorry for the trouble.
