### ISSUE TITLE
Papaparse not working with browserify

### ISSUE THREAD

**Issue by ChrisAlvares** [mholt/PapaParse#167]
Because of the way browserify module's work, the scope [here](https://github.com/mholt/PapaParse/blob/347befde6c8c6c4f23b0097b32e448e34fe28d15/papaparse.js#L1337 ) is not actually window. 

While the ```this``` keyword is good for keeping everything inclosed, the papaparse library uses the ```window.postMessage``` function, so the anonymous function must return ```window```,  otherwise you run into errors.

Before I submitted a PR, I wanted to get @mholt's opinion on if this is the right move here.

**Comment by mholt** [comment]
So just replacing `this` on line 1337 (see what we did there?) with `window`? I imagine that would be fine. Go ahead and submit a PR and we'll double-check.

*says the guy who's never used Browserify or RequireJS, or other Javascript modules/build tools, etc...*

**Comment by bluej100** [comment]
Sounds good to me. Thanks.

**Comment by robd** [comment]
I've been [getting PapaParse to work with webpack](http://stackoverflow.com/questions/28561396/loading-papaparse-dynamically-with-webpack), and I found I needed to use the [import and export loaders](http://webpack.github.io/docs/shimming-modules.html):

`require("imports?this=>window!exports?global.Papa!./papaparse.js")`

But if I change the script to pass `window` instead of `this` as suggested, I no longer need the import loader part (ie `imports?this=>window`). So I think this would be an improvement for webpack integration too.

**Comment by mholt** [comment]
How would changing `window` to `this` affect Node environments?

**Comment by robd** [comment]
I'm not sure I'm afraid. Guessing, I would say that the window object probably doesn't exist on the server side, so it would probably break. This seems to be being addressed here in BabyParse on [L845](https://github.com/Rich-Harris/BabyParse/blob/b7a7ef850d5720d17689e3df4b3daba5bbc9f965/babyparse.js#L845). 

Also [lines 830-843](https://github.com/Rich-Harris/BabyParse/blob/b7a7ef850d5720d17689e3df4b3daba5bbc9f965/babyparse.js#L830-L843) seem to handle returning the Papa object correctly for different module systems. I tried retrofitting these into PapaParse, and replacing calls to global.Papa with Papa - https://github.com/robd/PapaParse/compare/webpack-integration?expand=1. This was successful; it removed the need for any webpack loader shims and stopped Papa from being added to the window namespace when loaded as a module. 

Seems to make sense, and tests pass, but not sure whether this breaks anything. 

Probably still won't work in node, due to calls to `global.document`, `document`, web workers etc. But maybe a step in the right direction.

**Comment by ChrisAlvares** [comment]
I don't think PapaParse will work at all in node due to calling window.postMessage, so I am all for using @robd's solution.

**Comment by robd** [comment]
I believe all of the `window.postMessage()` calls are associated with the web worker code, so it might be possible to get it to work on node without web workers. 

Currently I think the first problem is that [`IS_WORKER`](https://github.com/mholt/PapaParse/blob/347befde6c8c6c4f23b0097b32e448e34fe28d15/papaparse.js#L10) will probably always be `true` on Node (since there will be no document available). `IS_WORKER` should be possibly only be set if `WORKERS_SUPPORTED` is true.

I've not tried any of this, but from looking at the code, if `WORKERS_SUPPORTED` and `IS_WORKER` were both false, this would guard a lot (all?) of the calls to `window.postMessage()`.

**Comment by robd** [comment]
OK, well the basic case works with node AFAICT with the change to `IS_WORKER` that I suggested:

`var IS_WORKER = (!!global.Worker && !global.document), LOADED_SYNC = false, AUTO_SCRIPT_PATH;`

I just tried with this quick script:

```javascript
require("./papaparse.js").parse("1,2,55,66", {
  complete: function(results) {
    console.log(results);
  }
});
```

Calling `PapaParse: node test.js`

Gives

```javascript
{ data: [ [ '1', '2', '55', '66' ] ],
  errors: [],
  meta: 
   { delimiter: ',',
     linebreak: '\n',
     aborted: false,
     truncated: false,
     cursor: 9 } }
```

**Comment by mholt** [comment]
@robd is right, as long as you don't try to use the browser-specific features in Node, you shouldn't encounter any problems. (Baby Parse has those features stripped out entirely.)

I like what Rob did -- maybe we could have a Node user confirm that things work alright in that environment and if so, go ahead and submit a PR? Would that fix all the issues discussed here?

**Comment by robd** [comment]
OK, I'll expand webpack-integration branch to include the `IS_WORKER` change. I could add some basic acceptance tests for node integration to `tests/test.js` perhaps using the long sample test data? I'm just thinking of exercising some of the main config options to see if they work.

I saw that you are thinking of moving over to a mainstream test runner at some point, but in the interim, should I just do a basic script which throws exceptions on failures? These cases could then be converted to tests / examples for whatever runner you choose when the time comes.

**Comment by robd** [comment]
OK, had a crack at this. Let me know what you think - PR #172

**Comment by mholt** [comment]
Wow, this is exciting - thanks for getting into the nitty-gritty to fix it! I'll look at it soon! (Or if @bluej100 checks it and is good with it, he can just merge it in. I'm pretty busy and I don't want to hold it up.)

**Comment by robd** [comment]
Thanks for merging #172 - glad it was helpful. @ChrisAlvares I think master should now work with Browserify - are you able to confirm? If so is it possible to come up with a basic integration test which shows that PapaParse works with Browserify? Perhaps we should also update the docs, release and close this issue.

I also wondered whether we should update the ReadMe to indicate that basic PapaParse functionality should now work with Node - probably #140 is the right place for that discussion.

**Comment by bluej100** [comment]
@ChrisAlvares , have you had a chance to try this out?

**Comment by ChrisAlvares** [comment]
Yes! This is working. Thanks for all the hard work on this gents.

**Comment by MaKleSoft** [comment]
Um, was this change reverted at some point? Having the same issue with importing as es6 module, since `this` is undefined in that case.
