### ISSUE TITLE
Longer string length please?

### ISSUE THREAD

**Issue by tomByrer** [mholt/PapaParse#174]
Though not strictly CSV, I'd like to parse this simple list:
```
away / aweigh
aye / eye / I
bail / bale
...
```
It could be helpful for other uses, eg Markdown table formatting of `-space-|-space- `.
Though I can hack the code myself, I'd prefer to use a maintained version (better for CDNs ect).
Could you not make [the limit](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L259) please?

**Comment by mholt** [comment]
The current HEAD actually doesn't enforce a delimiter length when using parse(), but you highlighted the restriction in unparse(), which is there because most parsers only support 1 character delimiters. Papa Parse follows the philosophy of "gracefully in, strictly out" to maximize interoperability.

So do you need the multi-char delimiter in unparse()? If you're just using parse(), try using the latest on master, which will be rolled into a release soon enough.

**Comment by mholt** [comment]
@tomByrer If there's anything else to say on this, feel free to comment and/or re-open, but I'm going to close this for now to tidy things up.
