### ISSUE TITLE
Why must I use BabyParse on node.js?

### ISSUE THREAD

**Issue by AtmoEntity** [mholt/PapaParse#261]
First of all, amazing project! This is going to be a major time saver.

Just a question though, why do you recommend using BabyParse for node.js everywhere? Is [this npm package](https://www.npmjs.com/package/papaparse) not official? What happens if I use papaparse in node?

**Comment by mholt** [comment]
Baby Parse was created as a fork of Papa Parse long ago before Papa Parse had any node.js compatibility. I kind of adopted it so I could keep it updated but since then pull requests have added some node compatibility to Papa Parse. If Papa Parse works for you sufficiently in node.js, then I'd recommend using it. Let me know how it goes (I don't use node.js), since it'd be nice to keep just one and sunset the other.

**Comment by AtmoEntity** [comment]
So I've done more research and it seems like the main reason PapaParse is incompatible is because of worker threads it uses?

I've `npm install`ed baby into my project and and up and running, but I'm still curious as to why papa wouldn't work.

**Comment by mholt** [comment]
Papa Parse is compatible with Node (or so I hear) so feel free to use Papa in Node - it should work as long as you don't try to do anything fancy (like web workers). Baby Parse was just specially made for Node.js but I think eventually I want to see if we can combine the two into Papa Parse to keep things simple.

Good question though. I should probably update the docs.
