### ISSUE TITLE
Error "The operation is insecure" when using workers

### ISSUE THREAD

**Issue by danielo515** [mholt/PapaParse#269]
Hello, using the following call to papaparse I get an error telling me that `The operation is insecure`

```
Papa.parse(element.files[0], {
                      worker: true,
                      step: function (row) {
		                        console.log("Row:", row.data);
                          	},
                      	complete: function () {
                      		console.log("Done!");
                      	}
                      });
```

Could you give me an advise about why?

**Comment by mholt** [comment]
Probably something to do with HTTP/HTTPS and browser security policies. What's the URL of your page and what does your script tag look like? Also which browser are you using and what is the exact output in the console?

**Comment by danielo515** [comment]
Hello @mholt 

Thank you very much for your answer.

I'm using angular, but my script on this case is fairly simple. I'm just accessing a file loaded by the user on an input type file. The portion of code I have pasted is just the onChange event listener of the input file input field. 

The problem seems to be with the usage of the `worker` if I remove the `worker:true` it works perfectly. The console reports an error on this portion of the code, line 1289:

`SecurityError: The operation is insecure. papaparse.js:1289:0`

```
		var w = new global.Worker(workerUrl);
```
I'm using the worker because the files I'm loading can be big, and the documentation proposes that as a fix.
Regards

**Comment by mholt** [comment]
Thanks for the console line. I still need your browser, the page URL, and the script tag that loads papa parse. I bet the page is violating the Same Origin Policy somehow.

**Comment by danielo515** [comment]
Hello @mholt 
The browser is firefox 41.0.2

The page URL is like `file:///C:/Users/index.html` 
The script tag that loads papa parse is quite simple also:  `<script src="../../PapaParse-4.1.2/papaparse.js"></script>`

I can't understand how the same function without workers does not violate the SOP and just adding a worker it does.

Regards

**Comment by mholt** [comment]
That's why. `file:///` pages aren't considered a domain name (or 'host'), so the browser can't safely let scripts load other scripts from host-relative URLs like `/scripts/papaparse.js` for instance. Workers require loading another script file since worker threads are executed in a separate global context.

So the solution is to serve your page under a real hostname like `localhost` or something else in your hosts file that loops back to your machine. I recommend using [Caddy](https://github.com/mholt/caddy) to run a quick local web server so you can load your site on `localhost:2015` (by default, anyway).
