### ISSUE TITLE
Strings containing inverted commas, being wrapped with inverted commas

### ISSUE THREAD

**Issue by micant** [mholt/PapaParse#272]
I'm having an issue when parsing JSON to CSV. If a string is passed in containing inverted commas it will wrap the whole string in inverted commas. Strings without inverted commas are parsed without inverted commas as expected.
``` 
A sentence like this containing "inverted commas".
```
The parsed sentence in the CSV will contain a line that looks like this
```
"A sentence like this containing "inverted commas"."
```
My config object looks like this
```
var csv = Papa.unparse(exportData, {
        delimiter: "\t",
        quotes: false
      });
```

I can't find an answer to this in the docs anywhere or if this is the expected or unexpected behaviour. Thanks!

**Comment by mholt** [comment]
Huh? Can you give an example of the input and the output exactly?

**Comment by micant** [comment]
I can replicate the issue with 
```
var csv = Papa.unparse([
	{
		"string": "foo \"bar\" "
	}
]);
```
I would expect this would return
```
foo "bar"
```
But I get
```
"foo ""bar"""
```

**Comment by mholt** [comment]
I'm confused. I thought "inverted comma" was like a "smart quote" - those look like regular double quotation marks. I just call those quotation marks. :stuck_out_tongue: 

Anyway, that's the expected output. Quotation marks need to be escaped with another quotation mark, and they need to be in a quoted field.

**Comment by micant** [comment]
Ah sorry, I probably used the wrong nomenclature in the title.. I'm talking about the standard quotation marks (that are used in declaring strings for javascript, for example), creating more quotation marks.

Excuse my ignorance, but I'm struggling to understand how this is the expected behaviour. If you escape a character within a string declaration, shouldn't that just be included in the string declaration? 

And where are all the extra quotation marks coming from? Thanks and apologies if I'm missing something really simple here.

**Comment by mholt** [comment]
The [CSV standard](https://tools.ietf.org/html/rfc4180) states that quotes in data need to be preceded by quotes in order to be escaped properly. Otherwise parsers won't know whether that quotation mark is part of the data or part of the delimiter. When you run `"foo ""bar"""` through a proper CSV parser, you will get `foo "bar"` as output, not to worry.

**Comment by micant** [comment]
Understood, thank you for explaining. I must be doing something wrong, as when I use 
```
var csv = Papa.unparse([
    {
        "string": "foo \"\"bar\"\" "
    }
]);
```
I get ``"foo """"bar"""""``

**Comment by mholt** [comment]
No, that's correct.

**Comment by goldins** [comment]
@mholt Sorry to comment on an old issue but I think this is the only issue that mentions smart quotes (not regular, straight, quotes). I need to be able to parse data copied from Microsoft Word into Excel, and often times there are smart quotes and other special characters (trademark, etc). I've hit a roadblock because they are represented differently from different sources:

```
echo e28099 | xxd -r -p
’
echo c395 | xxd -r -p
Õ
```

Note that the first parses as a ’ and not a regular ', but the second value is from Word/Excel. Unfortunately I don't have control over where the CSV comes from, so I was hoping you could help.

I can open a new issue if you prefer.

Thanks in advance.

**Comment by mholt** [comment]
@goldins I'd recommend doing a search+replace before parsing in that case.

**Comment by goldins** [comment]
@mholt thanks for the quick reply.

I think the root cause is that the encoding is MacRoman, which is a variation of ISO-8859-1.

This page lists the MacRoman and Unicode hex characters: http://www.alanwood.net/demos/macroman.html

Most character encoding match; A is 0x41 in MacRoman and U-0041 in ISO-8859-1.

Where I'm having trouble is that `d4` (for example) appears in two places:
- 0xD4 in MacRoman is a left single quotation mark
- U+00D4 in ISO-8859-1 is a Latin capital letter O with circumflex

I believe that both are represented as `d4` in the file. However, when parsing I don't know if the intended character is the ’ or the Ô, so search and replace might not be feasible.
