### ISSUE TITLE
Accept GZIP compressed files

### ISSUE THREAD

**Issue by wfwalker** [mholt/PapaParse#280]
When I use PapaParse to parse a CSV served by my gulp-connect server that doesn't do GZIP, everything works.

When I run PapaParse to parse a CSV served by github pages server that does do GZIP, I get "net::ERR_CONTENT_DECODING_FAILED"

``` javascript
    Papa.parse('./data/ebird.csv', {
        download: true,
        header: true,
        chunk: function(results) {
            document.getElementById('loading').textContent = gSightings.rows.length;
            gSightings.addRows(results.data);
        },
        complete: function(results) {
            document.getElementById('loading').textContent = 'loaded ebird data';
            routeBasedOnHash();
            gSightings.addToIndex(gIndex);
        },
    });
```

**Comment by mholt** [comment]
Yeah, Papa doesn't un-gzip files. Can you  confirm whether Papa's ajax requests have an Accept header that includes gzip? If so that is probably a bug. Or I would want the browser to decode it before getting to the script.

**Comment by wfwalker** [comment]
Thanks for the speedy reply! 

It appears to have that Accept header, yes -- here are the request headers as reported by Chrome dev tools:

<img width="542" alt="papa-headers" src="https://cloud.githubusercontent.com/assets/812428/12163043/61894df4-b4be-11e5-9cf1-de15ffe94559.png">

**Comment by mholt** [comment]
Okay, thanks for checking for me. Looks like we need to set the Accept header to be text/plain and text/csv. Are you handy with JS? Want to give it a try? (Should be one line of code I think.) I am just busy with another project.

**Comment by wfwalker** [comment]
I am experimenting with that one line, no luck so far. I can't set Accept-Encoding itself due to this policy:

https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

I can set the Accept header, but that doesn't seem to effect whether the response is GZIP or not.

**Comment by answerquest** [comment]
Hi, requesting devs to NOT do the header-changing thing permanently, and posting here for clarification for others who like me were looking for some way to make their pages "Accept GZIP compressed files" as the title states. 

I was searching for a way for PapaParse to load CSVs with GZIP compression from my linux based shared hosting server rather than the full CSV. I found out that the change had to be done from server end: https://forums.cpanel.net/threads/how-to-active-gzip-compression-for-all-my-websites.204412/ 

And now my page is loading the csv's blazing fast:  browser's developer console, network > XHR tab:
![screenshot-068](https://user-images.githubusercontent.com/9089552/41518952-cbdb1ae0-72e2-11e8-9d55-093b96001674.png)

Each row shows two sizes: darker one being the size of the loaded-up file, lighter one being the uncompressed version. It's a terrific amount of compression and has really sped up load times of not just this PapaParse page but everything else too.

So contrary to OP's experience, I'm finding PapaParse working just fine with gzip-enabled server. And I have also been using it on github pages site since a long time where the gzip compression happens by default and have never encountered errors of the kind shared. Here's the outer parts of my code:

	Papa.parse(csvfile, {
		download: true,
		header: true,
		skipEmptyLines: true,
		complete: function(results) {
		// do stuff with results.data
		} // end of complete function
	}); // end of papa.parse

Using PapaParse v4.3.2 currently. And my server is a shared hosting linux server with cpanel, hosted by Bigrock.

So, requesting devs not to permanently :  
> set the Accept header to be text/plain and text/csv. 

Perhaps we could create an option like `download:true` and let the users choose?

**Comment by pokoli** [comment]
I don't think we should create any option. If paparse is working correctly with gzip files is because the `XMLHttpRequest` is now uncompressing the gzip files which probably was not implemented when the issue was opened. 

So I think we are fine with the current behaviour: Accept gzip files if the server provide them and we should not do anything.

**Comment by do-me** [comment]
For anyone still looking for a quick solution: just use [pako.js](https://github.com/nodeca/pako/tree/master/dist) to unzip and papa parse afterwards. 

[https://gist.github.com/do-me/2d52460328810503da651c4e462b851f](https://gist.github.com/do-me/2d52460328810503da651c4e462b851f)

```javascript
function papa_load_default_csv(){
    fetch('data/test.csv.gz')
      .then(response => response.arrayBuffer())
      .then(buffer => pako.inflate(new Uint8Array(buffer)))
      .then(decompressed => {
        // convert binary data to string
        const decoder = new TextDecoder('utf-8');
        const csv = decoder.decode(decompressed);
        // parse csv with Papa Parse
        Papa.parse(csv, {
          delimiter: ';',
          dynamicTyping: true,
          skipEmptyLines: true,
          header: true,
          complete: function(results) {
            console.log(results.data);
          }
        });
      })
      .catch(error => console.log(error));
  }

// needs a webserver running
```
