### ISSUE TITLE
Custom headers when exporting JSON objects

### ISSUE THREAD

**Issue by codewzrd** [mholt/PapaParse#298]
I am using this library to import and export CSV. I get an array of JSON objects where the key is 2 to 3 characters but I need to have user friendly headings.

For example here is the JSON array:
[{ fn: 'Donald', ln: 'Trump', prty: 'Republican' },{ fn: 'Hillary', ln: 'Clinton', prty: 'Democrat' }]

I need the header to be First Name, Last Name, Party

I decided to make a change by modifying the "Specifying fields and data explicitly" version of unparse to include custom headers. Can I do a pull request?

**Comment by mholt** [comment]
What about a for loop to change the field names instead? Papa Parse already has the ability to specify custom field names when unparsing arrays.

**Comment by codewzrd** [comment]
Do you mean writing a for loop against the string result?

If I pass to Papa.unparse([{ fn: 'Donald', ln: 'Trump', prty: 'Republican' },{ fn: 'Hillary', ln: 'Clinton', prty: 'Democrat' }]); I will get back

fn,ln,prty
Donald,Trump,Republican
Hillary,Clinton,Democrat

If I use the override Papa.unparse({fields:["First Name, Last Name, Party"], data: [{ fn: 'Donald', ln: 'Trump', prty: 'Republican' },{ fn: 'Hillary', ln: 'Clinton', prty: 'Democrat' }] }) 

I just get back
First Name, Last Name, Party
because the custom field names don't match the JSON keys.


Thanks,

**Comment by mholt** [comment]
> Do you mean writing a for loop against the string result?

Not really, I meant write a for loop over the array of objects and change the field names (keys) to what you want them to be.

**Comment by codewzrd** [comment]
Ah, I see what you mean. That might work. I will try that.

**Comment by stevewillard** [comment]
I'm also interested in this feature. It would be great if there was an option, when parsing the headers of a CSV to transform them into a slug. For example, with `headers:true` on, and the first line of my CSV file looked like this:
```
First Name, Last Name, Birthday
```
I would like the keys to be transformed into:
```
{
    First_Name: "...",
    Last_Name: "...",
    Birthday: "..."
}
```

**Comment by mholt** [comment]
What's wrong with a for loop? Why add more complexity to this general-purpose library for a specific case?

**Comment by stevewillard** [comment]
That works too, I was just hoping to avoid looping over the data, especially for large data sets.

**Comment by mholt** [comment]
Yeah, I know. It's either your or Papa.

**Comment by lumitron** [comment]
I agree with @stevewillard I don't see the logic in looping through the data again just to change the name of the keys when there is the possibility of transforming header to keys. I don't see the reason why there can't be also the possibility to specify the headers by yourself like this for example:

```js
{
header: true,
customHeader: ["name_of_the_first_header", "name_of_the_second_header"]
}
```

Then you can have a table with a header in your language but in the code, you're working with the exact values you've specified. If there is **more headers** then columns then those **won't be used** and if there are **more columns** then headers then those **will be omitted** or it'll **throw error**. The code is so much cleaner in that case.

For example, I have a table with data that is administrated by client (let's say someone who doesn't know much stuff about computers). It's much more understandable for that person to see _**"Parent ID"**_ then _**"parentId"**_ and in my case that _**"Parent ID"**_ is in different language on top of that (which is **_"ID rodiče"_** in my case so there is diacritic just to make my life more miserable).

This is a really great library but I would be very glad if you'd just think about this idea for a moment because it would be a really neat feature! 😊

**Comment by PurvangShah** [comment]
According to requirements of @lumitron and some users, we need custom headers for CSV.
The approch to get custom headers when unparsing JSON to CSV is as below : 

1) Generate only headers with unparse  : 
         `const header = papa.unparse( { fields : ["Header 1 ", "Header 2", "Header 3"]... }, data : [] }, {header : true} ); `
 2) Un parse your actual JSON with specifying keys : 
         `parseData = papa.unparse ( { fields: ["key1","key2",...], data : [{ key1 : value }, {key2: value},...] } , { header : false , columns : ["key1","key2",...] });`
         `parseData = header + parseData;`

Custom header is appended without any loops and modifying object keys. 😊
