### ISSUE TITLE
$(...).parse is not a function

### ISSUE THREAD

**Issue by rahulTheDev** [mholt/PapaParse#359]
When i included the jquery min js it throwed an error that $(...).parse is not a function is not a function. Why?

Well when the script is created through javascript after the page loads the js works fine. But need to load the script while the page is loading.

Maybe it is conflicting with JSON.parse() function?

**Comment by pokoli** [comment]
@rahulTheDev you should use Papa.parse and Papa.unparse instead of $().parse for CSV parsing. 

Also I tested on a page which includes both jQuery and Parparse and everything is working as expected: 

$().parse()-> Calls jQuery parse
jQuery().parse() -> Calls jQuery parse
Papa.parse() -> Calls Papa parse

**Comment by pokoli** [comment]
Nothing to do on Paparse side. Please reopen if you don't agree.

**Comment by trickidicki** [comment]
- Make sure that papaparse is loaded after jquery
- note that async/defer may mess up load order
