### ISSUE TITLE
quoteChar option for parse

### ISSUE THREAD

**Issue by ZenVoich** [mholt/PapaParse#364]
There is quoteChar for unparse but not for parse.

**Comment by pokoli** [comment]
Hi @ZenVoich 

I don't understand which is the issue here. quoteChar option is avaiable for both parse and unparse. See:

- Parse: https://github.com/mholt/PapaParse/blob/master/tests/test-cases.js#L905
- Unparse: https://github.com/mholt/PapaParse/blob/master/tests/test-cases.js#L1166

Could you please elaborate which is the issue you are experimenting?

**Comment by ZenVoich** [comment]
Thanks. Just updated library and it works.
P.S. [Here](http://papaparse.com/docs#config) is missing the quoteChar option in parse config.

**Comment by pokoli** [comment]
Thanks for reporting it. I have updated the docs.

Fixed with https://github.com/mholt/PapaParse/commit/546edbecf85696330e94c3078675a6c6e9865f11
