### ISSUE TITLE
Performance page broken

### ISSUE THREAD

**Issue by AdamBJ** [mholt/PapaParse#369]
Seems like the performance page (http://jsperf.com/javascript-csv-parsers/4) is broken. This is what I'm getting when I try to run the performance test:

```
Uncaught TypeError: CSV is not a constructor.

message: Uncaught TypeError: CSV is not a constructor
fileName: http://jsperf.com/javascript-csv-parsers/4
lineNumber: 385
```

**Comment by pokoli** [comment]
HI @AdamBJ,

First of all, thanks for reporting the issue. 

I've run the test and realized that both paparse3 and paparse4 are working correctly. Reading the error message it seems that is related to another javascript library. 

I'm closing the issue as I understand that we do not have nothing to fix here. 

BYT: you can edit the jsperf performance with your github performance in order to fix the issue with the other libraries.
