### ISSUE TITLE
http headers when download is true

### ISSUE THREAD

**Issue by j--w** [mholt/PapaParse#374]
I may have missed this from the docs, but if I want to set an Authorization header on the request when streaming a file, is there a way to do so?

eg:
```
Papa.parse( 'some/endpoint.csv', {
	download: true,
	//downloadConfig: {headers:{authorization:'some token'}} was thinking an option like this may exist but haven't found reference to anything
	step: data => {
		console.log( data );
	},
	complete: this._subject.onCompleted
} );
```

**Comment by pokoli** [comment]
Hi, 

I'm sorry to say that is not currently suportted by PapaParse, but it will be a nice addition. If you dig in the code, you will notice that we are currently using [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) object in order to get the csv file. So in order to set the headers of the request we must use [setRequestHeader](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader) in order to set the headers. 

I think the easies whay is to add a downloadHeaders option in the Parser, which will be a dict with the headers to set on the Requests. If this option is present, we just have to call the setRequestHeader for each key and value. 

A PR in this way will be very welcome.

**Comment by j--w** [comment]
Thanks, I already have a branch with a primitive version of what you describe (right now it's just hard coding an option for Authorization header) that is working nicely, but I'll expand on that as you described. Any advice for writing a test for this? I haven't dug around the tests too much yet, but any input is appreciated.

**Comment by pokoli** [comment]
wow! this is great! I'm waiting for the PR to review it :) 

We currently does not have any test for the NetworkStreamer, so I think we won't have the infrastructure to test this feature with unit test. If we want to test this part we should be able to mock the request object and for me this is out of the scope of this issue. We can discuss it in a separate issue if you want to work on it.
