### ISSUE TITLE
Minor code formatting inconsistency

### ISSUE THREAD

**Issue by uvtzxpm** [mholt/PapaParse#386]
Some of the "newer" code is using spaces instead of the existing tabs formatting, for example:

https://github.com/mholt/PapaParse/blob/4d1e42b0ed151adbd981b3926aafb1f22d9a331c/papaparse.js#L196

You could make it consistent (either way) next time you work with the code. Thanks!

**Comment by pokoli** [comment]
I think I'm one of the ones how messed it a little bit, as I use spaces instead of tabs by default. 

I'm thinking in changing all the codebase to 4 spaces ident instead of tabs. The problem about this change is that we must enforce future contributions to follow this pattern and I don't know how to easly manage this. Any idea?

**Comment by pokoli** [comment]
@mholt I will like to have your opinion here please

**Comment by mholt** [comment]
I'm Team Tabs all the way -- less bytes, indent is customizable by editor, etc. Less backspacing too while editing.
