### ISSUE TITLE
Knowing the name of the parsed file in a multiple file parsing [without jQuery]

### ISSUE THREAD

**Issue by igalarza009** [mholt/PapaParse#499]
Hi!!

I need to use the data of multiple CSV files to create one unique file with a defined structure, so I've decided to parse each file into JSON using Papaparse and then calling my own parsing funcion to create the final file.

As long as I know, without using jQuery there's no implemented way to know when the parsing of multiple files has been completed, so I handle it myself:

![image](https://user-images.githubusercontent.com/22156100/39539495-0e976496-4e40-11e8-9d5f-092434b4a31f.png)

However, when the 'complete' callback of each parsing is reached, the loop is already over so the 'selectedFiles[i].name' variable makes actually no sense, giving an undefined result as expected. My problem is that I need to know the name of each file for my own parsing and I really can't find the way of knowing it. 

So, is there any property somewhere where I can find the name of the file currently parsed??

Thank you in advance!!

**Comment by pokoli** [comment]
I don't think we should manage file names on PapaParse as we also accept a string containing the values as input which won't have any filename.

Having said that, I think your problem is about variable scoping. Haven't tested but you can probably use the following pattern to solve it:

```
for () {
   var filename = selectedFiles[i].name;
   var compelete = function(results) {
         parsedFiles.push({
             'filename': filname,
             'data': results,
         });
   };
   Papa.parse(selectedFiles[i], {complete: complete});
}
```

Which will define on function for each filename with the correct variables references. 

Hope it helps.
