### ISSUE TITLE
Can I also parse xlsx file using this plugin?

### ISSUE THREAD

**Issue by ShahriatHossain** [mholt/PapaParse#524]
Can I also parse xlsx file using this plugin?

**Comment by pokoli** [comment]
No, only CSV files can be parsed. But you can save the file as CSV from Excel an it will convert it automatically. 

Once saved on CSV format it will be possible to parse it with this library

**Comment by adamreisnz** [comment]
Any future plans to support XLSX files directly? It adds quite a barrier for computer novices if we have to explain to them first how to convert their XLS files to CSV. I'm sure there's other plugins or projects out there that can convert XLS to CSV, but preferably we'd only use one library to do the lot.

**Comment by pokoli** [comment]
I don't think we should support excel parsing as the format is totally diferent from CSV.

So for me a separate library for xls parsing should be developed or used if it already exists.

**Comment by adamreisnz** [comment]
I understand it's different, and I'm not saying it should be included in the core of Papaparse, but perhaps as an optional plugin, maintained by the developers/collaborators of Papaparse? 

It can be hard to find a good library, and code quality and consistency will vary. I'd prefer to use a trusted plugin like Papaparse, which values qualities like speed, ability to handle large files, etc, rather than risk introducing another separate plugin, which may not have those same qualities.

Anyway, just a thought, no worries if you think it falls beyond the scope of this library.

**Comment by btakita** [comment]
From the xlsx documentation:

```
nodejs convert to CSV and write file (click to show)

var output_file_name = "out.csv";
var stream = XLSX.stream.to_csv(worksheet);
stream.pipe(fs.createWriteStream(output_file_name));
```
