### ISSUE TITLE
Decimal Digits for unparse

### ISSUE THREAD

**Issue by boldt** [mholt/PapaParse#531]
My usecase it to store numbers with two decimals digits even if the decimals are zero (i.e., `0.00`) while using unparse. My idea was to use `unparse` with `transform`, but [the docs](https://www.papaparse.com/docs#json-to-csv) do not allow transform for unparse.

I'm wondering, why `transform` is only available for `parse` and not for `unparse`.

**Comment by pokoli** [comment]
Hi @boldt, 

Yes transform is only available for `parse` because you do not control the input data (as it's a file). 
On the other hand, when you have a dict of values you have the control over the data and can apply any transform function before passing the values to unparse. Once the values are transformed you can pass them to PapaParse. 

I'm closing this issues as there is nothing to do from our side. 

Hope it helps.
