### ISSUE TITLE
Trouble load module in Meteor implementation

### ISSUE THREAD

**Issue by dylannirvana** [mholt/PapaParse#590]
I am relatively new to Meteor and am have trouble loading this module. I ran 
`meteor add harrison:papa-parse `
Then, importing into the app, 
`import { Papa } from 'meteor/harrison:papa-parse';`
But to no avail. I am getting either `[object Object]` errors or typeErrors, `Uncaught TypeError: Cannot read property 'parse' of undefined`, or `...'stream' of null`

**Comment by cfnelson** [comment]
@dylannirvana I'm guessing you've resolved this question? 

I imagine the original issue is due to mixing import syntax up an trying to import the default export as a named export which doesn't exist and caused you to have the `TypeError` message. i.e -> the default import would be  `import Papa from ...` instead of `import { Papa } from ...` is the named export, and I imagine their is no named export `Papa`.

Personally I'd recommend using the npm pkg directly instead of the meteor package. The npm pkg works great in Meteor. The below works in Meteor without any issues. 

```
meteor npm install papaparse
```

```js
import Papa from 'papaparse';

// dataToParse is whatever data you are trying to process.
const { data, errors, meta } = Papa.parse(dataToParse, {
  header: true,
  skipEmptyLines: true,
  dynamicTyping: false,
});
```

**Comment by pokoli** [comment]
Thanks @cfnelson for resolving this question.
