### ISSUE TITLE
transformHeader

### ISSUE THREAD

**Issue by ptorrent** [mholt/PapaParse#597]
Hello,

I'm not able to call transformHeader

```javascript
Papa.unparse(data,{
	delimiter: ";",
	header: true,
	transformHeader:function(h){
		console.log('HEADER',h)
		if(h == 'key') return  'test'
		return h
	}
})
```

"transformHeader:function" doesn't exists in the version "v4.6.2" ?

Thanks for your support and your great work !

**Comment by pokoli** [comment]
Hello, 

The transformHedaer function is only available on 5.0.0 version which is currently unreleased and only available on master branch using non minified file.

**Comment by rebz** [comment]
@pokoli Is there an ETA on 5.0? Or is it possible to get early access? I'm a bit too excited for this. :)

**Comment by pokoli** [comment]
@rebz tehere is no ETA for now, I will probably create some pre-releases on npm in order to allow users test it before the final release. 

For now you can use the papaparse.js file from the master branch on this repository. 
If you need the minified version you can compile it with the grunt commant 

Hope it helps

**Comment by dawnfantasy** [comment]
Please add a note in the docs file to save us some time!

**Comment by pokoli** [comment]
@dawnfantasy feel free to open a pull request improving the docs. They are on the docs folder in this repository
