### ISSUE TITLE
5.0.0-beta0 - Step function behavior differs when run under a web worker

### ISSUE THREAD

**Issue by optical** [mholt/PapaParse#613]
It looks like in 5.0.0-beta0 the step callback is invoked with different arguments depending on whether parsing is done in a worker or not.

See this fiddle: https://jsfiddle.net/o3uv7ynx/

When run with worker: false, the first argument is a cell (string), rather then a row (string[]).
When run with worker: true, the first argument is a row (string[]).

It looks like the desired behavior is the latter

**Comment by pokoli** [comment]
After reviewing the proposed file I that the returned values is a string[] containing only one row. Previously the values was an array of string[], so that's why your older code does not work on this new version.

You should update your code example changing:

`      const line = result.data[0];`
to 
`      const line = result.data;`

and everything will work as expected.

From the API point of view the behaviour is consistent when using worker and non worker.

**Comment by optical** [comment]
Hi,

I understand the API has changed, however that is not what I am trying to report.
If you run the code in the fiddle with worker: true, result.data is a string[]. When worker is false, result.data is just `string` as you describe. So that behaviour is inconsistent.

**Comment by pokoli** [comment]
Are you sure when non using worker the step is called with string? [There is a test that ensures it is called with an array. ](https://github.com/mholt/PapaParse/blob/master/tests/test-cases.js#L1793)

Could you please share a sample code which calls the step function with and string?

**Comment by optical** [comment]
That test looks the behaviour I'd expect.
The code is in the fiddle I included in the original post. Here it is: https://jsfiddle.net/o3uv7ynx/2/

When worker is false, this is the result:
![image](https://user-images.githubusercontent.com/767001/50888640-03369900-145b-11e9-8b38-d972987afb96.png)

If you load the fiddle and hit the "test" button you'll run the snippet. Change the value of worker to see the differing behaviour.

**Comment by pokoli** [comment]
[I've already explained](https://github.com/mholt/PapaParse/issues/613#issuecomment-452617306) that there is an error on the fiddle, updating with the changes I posted work as expected for me.

**Comment by optical** [comment]
That isn't the issue I am talking about. Here, let me rewrite it in the hopes the behaviour is more clear.
New fiddle: https://jsfiddle.net/yn8jz14p/2/

![image](https://user-images.githubusercontent.com/767001/50890593-5e6a8a80-145f-11e9-8845-3a7d4c99558e.png)

Sorry for any confusion in the original fiddle, I realise the initial version uses the V4 format which has changed, so maybe thats confusing things. The issue is the consistency with worker true/false.

**Comment by pokoli** [comment]
It seems an implementation detail as if I print the values I see the same exact result.

Could you investigate from which type is each result?

**Comment by optical** [comment]
Sure, with worker:true result.data is string[][].
![image](https://user-images.githubusercontent.com/767001/50927954-247ca100-14be-11e9-8c5e-5359f795a5e7.png)

With worker: false result.data is string[]
![image](https://user-images.githubusercontent.com/767001/50928025-5261e580-14be-11e9-9100-e4049a7b0adf.png)

**Comment by ditiem** [comment]
I was testing the new version of papaparse because I need the `transformHeader` function, but the argument that it receives is a string (the code is not in a worker) and it contains only 1 character.

Additionally, the same thing happens in the `step` function, only the first character of the data is past as argument. You can quickly see there is a bug in the Demo page by clicking on the "Stream" option.

Things work fine if the `step` function is not provided and only `complete` function is provided.

I hope this gives you all some hint.

**Comment by jsg2021** [comment]
I've noticed this as well.

**Comment by jsg2021** [comment]
When from the worker, the `results` object is rebuilt...
https://github.com/mholt/PapaParse/blob/71c2eee63c7249460571be04630e1f18c003fe2c/papaparse.js#L1710

But when not it's just passed straight in....
https://github.com/mholt/PapaParse/blob/71c2eee63c7249460571be04630e1f18c003fe2c/papaparse.js#L1015

**Comment by jsg2021** [comment]
Awesome!
