### ISSUE TITLE
.parse converting empty string to null?

### ISSUE THREAD

**Issue by MayaGans** [mholt/PapaParse#710]
I firstly wanted to thank you for this incredible tool! I was curious - it looks like setting `dynamic typing: true` turns empty strings into `null`? dynamic typing is rad, is there any way to override just this one feature? 

# Clarification 

The csv:
```
number,string
1,one
undefined,"two"
3,undefined
4,
,five
6,""
```

Returns:
```
 [
      {number: 1, string: 'one'},
      {number: undefined, string: 'two'},
      {number: 3, string: undefined},
      {number: 4, string: null},
      {number: null, string: 'five'},
      {number: 6, string: null}
]
```

But I'd like it to return
```
 [
      {number: 1, string: 'one'},
      {number: undefined, string: 'two'},
      {number: 3, string: undefined},
      {number: 4, string: ''},
      {number: '', string: 'five'},
      {number: 6, string: ''}
]
```

Is this possible?

**Comment by MarcBT** [comment]
Hi, thanks @MayaGans for submitting this.
I came here to discuss the same use case !

I looked at https://github.com/mholt/PapaParse/pull/464 that introduced this behavior.
@mfds, @pokoli what was the motivation to introduce `null` value here ?

In my use case, papaparse output feeds is then converted to a `xlsx` file.
Having `null` values in the json file leads to the issue describe in https://github.com/agershun/alasql/issues/442#issuecomment-446711163

Meanwhile, I've downgraded to the v4.1.2.

Thanks in advance for your feedback and thanks for this tool !

**Comment by jonrandahl** [comment]
Thanks from me as well @MayaGans! 

We're experiencing this issue too and I wondered if there would be any way to keep the dynamic numeric and boolean data types but still have empty strings instead of null?

We're currently using v4.6.2 but I am hesitant to update to latest if we will still experience the same issue?

Thanks in advance too!

**Comment by lamuertepeluda** [comment]
Hi there,

I also agree that using `null` for empty values is an arbitrary choice and can mess around with many things, from databases to validators (for instance, I use JSONSchema/Ajv). 
I think this should be best set somewhere in the config, something such as `config.defaultEmptyValue: null`, then let the user choose.

The problem surely is originated from this code:

https://github.com/mholt/PapaParse/blob/49170b76b382317356c2f707e2e4191430b8d495/docs/resources/js/papaparse.js#L1185

## Workaround

The workaround I've found to get the `undefined` values for empty strings (which I needed) is the following:

```js
const { parse } = require('papaparse')

// copy same regex used by parse
const FLOAT = /^\s*-?(\d*\.?\d+|\d+\.?\d*)(e[-+]?\d+)?\s*$/i
const ISO_DATE = /(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))/;

// rewrite parseDynamic to return undefined
function parseDynamicReturningUndefined(value, field) {
  if (value === 'true' || value === 'TRUE') {
    return true
  } else if (value === 'false' || value === 'FALSE') {
    return false
  } else if (FLOAT.test(value)) {
    return parseFloat(value)
  } else if (ISO_DATE.test(value)) {
    return new Date(value)
  } else return value === '' ? undefined : value
}

// csvFileContent = string with csv file
const x = parse(csvFileContent, {
  dynamicTyping: false, // important, or will be called after transform
  transform: parseDynamicReturningUndefined,
  header: true
}).data
```

Of course you can do many different things with this technique, e.g. use moment.js for date parsing instead of the above regex, and so on...

**Comment by pokoli** [comment]
Using null allows to diferentiate which cell is empty and which has a bank value. 
I'm wondering which values we should expect for empty values. Do you have any other values than blanks and nulls? If so I do not think it deserves adding a configuration.

BTW: Once the file is parsed you replace nulls with '', which will provide the expected result.

**Comment by lamuertepeluda** [comment]
Well blank, or undefined, is different than null, or empty strings in JS. They have different typeof, for instance, although all of them are falsey. 
Using undefined would differentiate the empty cell all the same.
I think using transform as above should solve most issues for those needing non-null values, like me.

Using transform does not require another post-processing of the files (e.g. data.map(...) ) to transform null to something else.

**Comment by pokoli** [comment]
Ok, so i'm closing this issue as there is nothing that we should change on PapaParse to make this work.

**Comment by edwinrosemond1** [comment]
I know this issue is closed but I came across this and thought the inverse of @lamuertepeluda solution could also work. So you keep dynamicTyping as True and just address your empty strings. So your transform function looks something like this:
`  const tranformFunction = (value, column) => {
    if (value === "") {
      return undefined;
    } else {
      return value;
    }`
