### ISSUE TITLE
Option to skip duplicate lines

### ISSUE THREAD

**Issue by ornic** [mholt/PapaParse#758]
It would be very helpful to be able to get only data from unique rows in the results.

**Comment by pokoli** [comment]
I think the concept of "duplicate" is something dificult to determine because it is diferent for each person using PapaParse. Having said that I think it's better to keep paparse as is so each developer can filter the duplicated rows once procesed, which fits the PapaParse principible of parsing only rows and delegate other functionalities to its users.
