### ISSUE TITLE
Protection against CSV injection attacks

### ISSUE THREAD

**Issue by wcerfgba** [mholt/PapaParse#793]
When importing a CSV file, Microsoft Excel and LibreOffice Calc will both interpret cells beginning with a `=` as formulae, which can lead to attacks that can result in data exfiltration or arbitrary command execution. [1] This is easily remedied by prefixing cells that begin with `=`, `+`, `-` or `@` with a `'` in order to suppress automatic interpretation of formulae by these softwares. [2]

I would like to propose an option `escapeFormulae` for `Papa.unparse` to provide this prefixing behaviour.

Thanks!

[1] https://owasp.org/www-community/attacks/CSV_Injection
[2] https://www.contextis.com/en/blog/comma-separated-vulnerabilities

**Comment by pokoli** [comment]
That make sense for me.

I'm wondering if we should activate this option by default or not.

**Comment by wcerfgba** [comment]
> I'm wondering if we should activate this option by default or not.

I guess this is dependent on if you have users who currently rely on formulae interpretation and for whom this would break on an upgrade. My intuition is that this would be a minority of users and that for most use cases, it would be better to be safe by default, and have `escapeFormulae` default to `true`.

**Comment by pokoli** [comment]
Having a safer default sounds good to me. Then we just need to have a proper documentation to explain why the should should be desactivated and include a warning about the it's safety risks.

So we just need an implmentation for it.

**Comment by dylanlingelbach** [comment]
> Having a safer default sounds good to me

I'm sorry but this doesn't make sense to me. `papaparse` is a CSV parser. By default modifying the contents of a CSV file that may or may not ever get processed by Excel/LibreOffice seems like very odd behavior.

This bug is reported as a [high severity vulnerability](https://snyk.io/vuln/SNYK-JS-PAPAPARSE-569101) which also doesn't make sense to me - by that logic every text editor has the same vulnerability

**Comment by pokoli** [comment]
@dylanlingelbach not all contents are modified but only the ones that are suceptible of having a formula, just the ones that start with `=` which from my understanding should not me the bast majority. 

But I agree that this should not be treated as high severty (at least on Papaparse) because:

- The file may not be openend by a SpreadSheet software, so this users are not afected.
- There is no evidence how the attacker can gain access to the input data to include the formulas and how to let the user execute it.

P.S: My main usage of `papaparse` is to generate files to be opened by a SpreadSheet software, so probably I'm a little bit biaged here. I will like to have more opinion on this.

@mholt @dboskovic what do you think it should be the defalut value of this new parameter?

**Comment by asafbiton** [comment]
Hi there!

My name is Asaf and I'm part of the Snyk Security Team. We have been tracking this issue for a few days now, and an advisory has been mistakenly published. I tend to agree with all the above arguments and **do not believe** there is a vuln within the context of `papaparse`.

I have therefore revoked this advisory from our database. I apologize for any inconvenience caused by this.

For further inquiries please don't hesitate to contact us at report@snyk.io or using the [vulnerability disclosure form](http://snyk.io/vulnerability-disclosure/).

**Comment by pokoli** [comment]
@asafbiton Thank you so much!

**Comment by dylanlingelbach** [comment]
@asafbiton thank you!

@pokoli I think if _any_ contents of the CSV file are modified by default that is odd (CSV quoting/escaping excluded)

**Comment by wcerfgba** [comment]
Sorry I have been away from the thread for a few days. Would it be fair to say the consensus is that this option is a good idea, but it should be disabled by default? I am happy to write a patch some point this week if we are aligned on this. :)

**Comment by shawn-eary** [comment]
@dylanlingelbach 
> I'm sorry but this doesn't make sense to me. `papaparse` is a CSV parser. By default modifying the contents of a CSV file that may or may not ever get processed by Excel/LibreOffice seems like very odd behavior.

I agree many people don't give a rip if a file processed by papaparse contains Macro, Command or SQL injection attacks, but some users might appreciate a PapaParse "plugin" that will alert them if the parsed file seems suspicious. If a probable attack is found, it might be useful for the PapaParse "plugin" to state the line and/or char number where the suspect text is.

**Comment by dylanlingelbach** [comment]
> some users might appreciate a PapaParse "plugin" that will alert them if the parsed file seems suspicious

Agreed there! Modifying the data just shouldn't be default behavior for a CSV parser

**Comment by shawn-eary** [comment]
@dylanlingelbach 
> Agreed there! Modifying the data just shouldn't be default behavior for a CSV parser

How about overloading the Parse function to accept the following optional arguments?:

1. User defined function that runs on each field and returns true if the user thinks the field contains suspicious patterns
2. User defined function that runs a transform on each field

PapaParse could then provide standard functions that the user could chose from to pass in for Item 1 and Item 2 above. If the user passes in nothing, PapaParse would behave the say way it has for years.

NOTE: About Item 1 above, if a function is passed in for this parameter and that function returns true, PapaParse would then alert the user with an appropriate warning so she/he can begin mitigation.

**Comment by mholt** [comment]
I think interpretation of the data is out of scope for a CSV parser and lends itself to more security problems, not less.

**Comment by shawn-eary** [comment]
I apologize, PapaParse **already** supports a transform function. I'm sorry I didn't see this in the manual... The already supported transform function not only allows you to remove risky values from CSV cells, but it also allows you to identify them if you don't mind using "global" variable style programming: 

```JavaScript
  var globalRisksFound = []; 
  function isRisky(v, cName) {
    // Grossly over conservative
    var isAlphaNumeric = v.match(/^ *[A-Za-z0-9 ]+ *$/)
    if (!isAlphaNumeric) {
      globalRisksFound.push(
        {
          col: cName, 
          val: v
        }
      );
    }
    // Don't do a transform. Just report the error
    return v;
  }

  let resultingJSON = PapaParse.parse(
    uploadedData,
    {delimiter: ",", header: true, transform: isRisky}
  );
  
  // The suspect values are now in the globalRisksFound array
```

I think a **cool** enhancement someday might be for the transform function to pass the record number via a third parameter.

**Comment by DE-Kato** [comment]
Dear @mholt 

Notice:
There seems to be a mistake in the formula that checks for the presence of the escapeFormulae option.

https://github.com/mholt/PapaParse/blob/master/papaparse.js

**wrong**
> } else if (typeof _config.escapeFormulae === 'boolean' && _config.escapeFormulae) {

**correct**?
> } else if (typeof (_config.escapeFormulae === 'boolean') && _config.escapeFormulae) {

Setting "escapeFormulae: false" results in the same behavior as when "escapeFormulae: true" is set.
I can't take the time to create a pull request for a fix 🙏, but I hope this helps. 😉

Thank you
