### ISSUE TITLE
Feature: Flatten in Json to CSV

### ISSUE THREAD

**Issue by timot7782** [mholt/PapaParse#822]
Hi,

Can we have an option in `config` to flatten the JSON before converting to CSV. Yes, I can use a lib for that, I thought it would be nice if it is a built-in, making this library an all-around json to csv vice versa

Eg.
JSON
```
[
  {
    "Id": "1",
    "Account": {
      "Id": "A1"
    },
    "Contact": {
      "Id": "C1"
    }
  },
  {
    "Id": "2",
    "Account": {
      "Id": "A1"
    },
    "Contact": {
      "Id": "C2"
    }
  }
]
```

Flatten
```
[
  {
    "Id": "1",
    "Account.Id": "A1",
    "Contact.Id": "C1"
  },
  {
    "Id": "2",
    "Account.Id": "A1",
    "Contact.Id": "C2"
  }
]
```

CSV
```
"Id", "Account.Id", "Contact.Id"
"1","A1","C1"
"2","A1","C2"
```

**Comment by pokoli** [comment]
Hi, 

Thanks for your suggestion but I think we should reject it. PapaParse is a library for parsing and unprasing CSV files but it is not designed to transform data. It is up to the user of the library to pass the data in the right format. 

I may understand that you think it will be great to have this feature for your use case, but we can not add all the transform functions that our users may require otherwise we will become a blotated library and this will for sure have a penanlty on our performance. 

Thanks for your comprehension!
