### ISSUE TITLE
Option to set BOM?

### ISSUE THREAD

**Issue by karland** [mholt/PapaParse#830]
Hi, thanks for PapaParse. 

I tried to understand, how the BOM is handled for unparse. Apparently, Papa has Papa.BYTE_ORDER_MARK = '\ufeff';

Basically what I would like to achieve is to generate from a JSON a CSV with a BOM byte, so that Excel recognizes the UTF8. But I cannot set an option in the config for unparse. Is this correct? Is this desired behaviour?

Thanks a lot.

**Comment by pokoli** [comment]
Hi, 

Currently PapaParse does not have an option to set the BOM, but is really possible to set it after unparse:

```
var csv = Papa.unparse(data, {});
csv = '\uFEFF'+ csv;  
```

I'm not sure if it's worth adding a configuration for this simple code

**Comment by karland** [comment]
@pokoli Thanks a lot. The code is really simple, you are right. Currently I would like to use PapaParse ideally through `react-papaparse` from @Bunlong because I would need the upload and the download functionality. [`react-csv-downloader`](https://github.com/dolezel/react-csv-downloader#props), for instance, is exposing the bom functionality.

But, since this config is not exposed, it might be difficult to get it through libs that build on PapaParse? What do you think?

**Comment by pokoli** [comment]
For me the main issue is that the BOM should only be added for downloading the file to Excel.

As PapaParse is generting a file and not managing the download of it Probably it makes sense to add the BOM to the downloader library. 

What do you think?

P.S: We are have implemented [this feature in Tryton](https://hg.tryton.org/sao/rev/5247d0b71e4d) and we only set the BOM when exporting to windows system because there is no Excel on Linux

**Comment by karland** [comment]
Ok, thanks. You are right and I perfectly agree. Thanks a lot.
