### ISSUE TITLE
skipEmptyLines unable to remove ZERO WIDTH SPACE

### ISSUE THREAD

**Issue by wahackr** [mholt/PapaParse#917]
https://www.fileformat.info/info/unicode/char/200b/index.htm

using `charCodeAt` to display the code is 8203

no matter the value is 'greedy' or true

**Comment by Clonkex** [comment]
I ran into this issue today. Normally when working with UTF-8 files I just save them as plain old UTF-8 without a BOM. However this time I needed to open it in Excel (which, in typical Microsoft fashion, doesn't detect UTF-8 encoding unless there's a BOM) so I changed the encoding (with the encoding menu in Notepad++) to include a BOM. Turns out, NodeJS doesn't strip the BOM when reading files (which I think is just plain dumb, but we won't get into that). Since I have headers in my CSV, I end up with the zero-width space character preceding the first header string on every row.

This seems to be the canonical Github issue regarding this problem:
https://github.com/nodejs/node-v0.x-archive/issues/1918

From that I even see another PapaParse issue where someone ran into the BOM issue:
https://github.com/mholt/PapaParse/issues/840

See here for some workarounds:
https://stackoverflow.com/questions/24356713/node-js-readfile-error-with-utf8-encoded-file-on-windows

**Comment by peteruithoven** [comment]
My workaround was to copy the [stripBom function](https://github.com/sindresorhus/strip-bom/blob/main/index.js) from the populair [strip-bom](https://www.npmjs.com/package/strip-bom) package and use that before having papaparse parse the data.
