### ISSUE TITLE
Typescript error on Parse remote files

### ISSUE THREAD

**Issue by HasinaNjaratin** [mholt/PapaParse#923]
I use the lib in typescript.

```
import Papa from 'papaparse';

Papa.parse(filePath, {
  download: true, 
};
```

`filepath` type is `string`

I get error on filePath:

`No overload matches this call. The last overload generated the following error. The 'string' type argument is not assignable to the 'unique symbol' type parameter.`

**Comment by vincerubinetti** [comment]
FWIW... I was getting this error, but because of a different problem. I was passing a non-function to the `complete` option (i.e. I accidentally did `complete: foo()` instead of `complete: () = foo()`), and for some reason it was throwing a fit about the `createReadStream()` I was passing for the first argument. I think something's wonky about type overloads or something.
