### ISSUE TITLE
Trying to read the every line in the csv file 

### ISSUE THREAD

**Issue by koloyyee** [mholt/PapaParse#960]
Hi everyone, I am trying to parse a csv file with over 17k+ lines in a React application but it didn't return all lines and sometimes returned a weird number of lines, anyone knows what went wrong? Thanks in advance!
I did a bit of StackOverflow searching I found this 
![image](https://user-images.githubusercontent.com/23250355/203083201-17375857-8b8e-4dd7-a75e-72ef989b7df9.png)

but it didn't return all 17k lines but 13k  instead 
![image](https://user-images.githubusercontent.com/23250355/203082618-56ddd7b2-59eb-4eac-bcdf-b2c7100b544a.png)
and the return number of lines will be different every time I save my tsx file.
![image](https://user-images.githubusercontent.com/23250355/203083393-cd0602f0-9cdc-4233-9e2d-702ab9f41e71.png)

therefore I have to search for another package that returns 17k+ lines
![image](https://user-images.githubusercontent.com/23250355/203082797-ecb76c22-dddd-43f0-bc84-c6c1d31cd513.png)
![image](https://user-images.githubusercontent.com/23250355/203082924-b2779c50-a9a4-4820-b31f-4612c415a864.png)

**Comment by pokoli** [comment]
Hi, 

This bug tracker is just for reporting incidents or improvement with the library but it seems there is no problem on our side but some wrong usage from your side. So I'm closing this issue. 

If there is something wrong with papaparse please provide a minimum tests case to reproduce the problem otherwise we can not fix it. 

Thanks.

**Comment by koloyyee** [comment]
ok thanks
